
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
import guiKey
import guiSign
import guiVerify


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class Landing(Frame):
    def __init__(self, master):
        Frame.__init__(self, master, width = 1200, height = 800, bg = "#FFFFFF")
        
        self.canvas = Canvas(
            master,
            bg = "#FFFFFF",
            height = 800,
            width = 1200,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.place(x=0,y=0)

        # self.myScrollbar = Scrollbar(master, orient=VERTICAL, command= self.canvas.yview)
        # self.myScrollbar.pack(side=RIGHT, fill=Y)

        self.canvas.create_text(
            418.0,
            277.96044921875,
            anchor="nw",
            text="Digital Signature",
            fill="#000000",
            font=("Poppins", 42 * -1)
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiKey.GenerateKey),
            relief="flat"
        )
        self.button_1.place(
            x=309.3465576171875,
            y=382.693115234375,
            width=580.4949951171875,
            height=66.29400634765625
        )

        self.button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        self.button_2 = Button(
            image=self.button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiSign.Sign),
            relief="flat"
        )
        self.button_2.place(
            x=309.3465576171875,
            y=492.8431396484375,
            width=580.4949951171875,
            height=66.29400634765625
        )

        self.button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        self.button_3 = Button(
            image=self.button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.master.switch_frame(guiVerify.Verify),
            relief="flat"
        )
        self.button_3.place(
            x=309.3465576171875,
            y=602.9931640625,
            width=580.4949951171875,
            height=66.29400634765625
        )
        self.canvas.create_text(
            600.0,
            693.128662109375,
            anchor="n",
            text="Created by:",
            fill="#000000",
            font=("Poppins ExtraBold", 16 * -1)
        )
        self.canvas.create_text(
            600.0,
            713.128662109375,
            anchor="n",
            text="18220049 Rachmad Hidayat, 18220057 Muhammad Ardi Avicenna, 182200095 Tubagus Baraka Kautsar S.",
            fill="#000000",
            font=("Poppins ExtraBold", 16 * -1)
        )

        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            616.9901123046875,
            148.0,
            image=self.image_image_1
        )

# window.resizable(False, False)
# window.mainloop()
